CREATE TABLE QUERY1 
AS (SELECT G.NAME,COUNT(H.MOVIEID) AS MOVIECOUNT
    FROM GENRES G, HASAGENRE H
    WHERE G.GENREID=H.GENREID
    GROUP BY G.NAME);


CREATE TABLE QUERY2 
AS (SELECT G.NAME, AVG(R.RATING) AS RATING
    FROM RATINGS R, GENRES G, HASAGENRE H
    WHERE (R.MOVIEID=H.MOVIEID AND H.GENREID=G.GENREID)
    GROUP BY G.GENREID);


CREATE TABLE QUERY3 
AS (SELECT M.TITLE, COUNT(R.RATING) AS COUNTOFRATINGS
    FROM MOVIES M, RATINGS R
    WHERE (M.MOVIEID=R.MOVIEID)
    GROUP BY M.MOVIEID
    HAVING (COUNT(R.RATING)>=10));


CREATE TABLE QUERY4 
AS (SELECT M.MOVIEID,M.TITLE
    FROM HASAGENRE H, MOVIES M, GENRES G
    WHERE (M.MOVIEID=H.MOVIEID AND
    H.GENREID=G.GENREID AND
    G.NAME='Comedy'));


CREATE TABLE QUERY5 
AS (SELECT M.TITLE, AVG(R.RATING) AS AVERAGE
    FROM RATINGS R, MOVIES M
    WHERE (R.MOVIEID=M.MOVIEID)
    GROUP BY M.MOVIEID);

CREATE TABLE QUERY6 
AS (SELECT AVG(R.RATING) AS AVERAGE
    FROM RATINGS R, HASAGENRE H
    WHERE (R.MOVIEID=H.MOVIEID
    AND H.GENREID 
    IN (SELECT G.GENREID
        FROM GENRES G
        WHERE G.NAME='Comedy')
        )
    );

CREATE TABLE QUERY7 
AS (SELECT AVG(R.RATING) AS AVERAGE
    FROM RATINGS R
    WHERE (R.MOVIEID
            IN (SELECT H.MOVIEID FROM HASAGENRE H
                WHERE H.GENREID
                    IN (SELECT G.GENREID FROM GENRES G
                        WHERE G.NAME='Comedy')
                INTERSECT
                SELECT H.MOVIEID FROM HASAGENRE H
                WHERE H.GENREID
                    IN (SELECT G.GENREID FROM GENRES G
                        WHERE G.NAME='Romance')
                )
        )
    );


CREATE TABLE QUERY8
AS (SELECT AVG(R.RATING) AS AVERAGE
    FROM RATINGS R
    WHERE (R.MOVIEID
            IN (SELECT H.MOVIEID FROM HASAGENRE H
                WHERE H.GENREID
                    IN (SELECT G.GENREID FROM GENRES G
                        WHERE G.NAME='Romance')
                EXCEPT
                SELECT H.MOVIEID FROM HASAGENRE H
                WHERE H.GENREID
                    IN (SELECT G.GENREID FROM GENRES G
                        WHERE G.NAME='Comedy')
                )
        )
    );


CREATE TABLE QUERY9 
AS (SELECT MOVIEID,RATING
    FROM RATINGS
    WHERE USERID= :v1);


CREATE TABLE SIMILARITY
AS (SELECT M.MOVIEID AS MOVIEID1,N.MOVIEID AS MOVIEID2,(1-(ABS(X.AVERAGE-Y.AVERAGE)/5)) AS SIM
FROM QUERY5 X, QUERY5 Y,MOVIES M,MOVIES N
WHERE (X.TITLE=M.TITLE AND Y.TITLE=N.TITLE
        AND M.MOVIEID <> N.MOVIEID AND
        M.MOVIEID NOT IN (
            SELECT MOVIEID FROM QUERY9
        )
        AND N.MOVIEID IN (
            SELECT MOVIEID FROM QUERY9
        )
        ));

CREATE TABLE RECOMMENDATION 
AS (SELECT M.TITLE
    FROM SIMILARITY S, RATINGS R,MOVIES M
    WHERE (R.MOVIEID=S.MOVIEID2 AND R.USERID=:v1 AND S.MOVIEID1=M.MOVIEID)
    GROUP BY M.TITLE
    HAVING SUM(S.SIM*R.RATING)/SUM(S.SIM)>3.9);


DROP TABLE SIMILARITY;